### ISSUE TITLE
remove functions? indexes_connectivity_intrabrain

### ISSUE THREAD

**Issue by phoebsc** [GHFC/HyPyP#11]
Now that compute_sync is handling inter- and intra-brain synchrony at the same time, I'm wondering if we still need these functions in analyses.py.

**Comment by deep-introspection** [comment]
@phoebsc is it still an issue?

**Comment by Fbrun18** [comment]
That is true, and this is the same for split and merge!

**Comment by deep-introspection** [comment]
@Fbrun18 & @phoebsc Can we close this issue then?
