### ISSUE TITLE
`dir(hypyp)` get an empty list of function.

### ISSUE THREAD

**Issue by AmirDJV** [GHFC/HyPyP#18]
When I run `dir(hypyp)` or `inspect` I get an empty list of function. 

![image](https://user-images.githubusercontent.com/25877896/82945562-d3cbf200-9fa5-11ea-8a5b-ba9e0aec6154.png)

![image](https://user-images.githubusercontent.com/25877896/82925149-05cd5c00-9f86-11ea-8d5a-9f80558f125c.png)

**Comment by YannBeauxis** [comment]
What functions do you expect to get ?
To attach some attributes or function to a module you should use `__init__.py` to import and use `__all__` attribute like that :
```
from .analyses import PSD

__all__ = ["PSD"]
```

**Comment by AmirDJV** [comment]
According the [`dir` docs](https://docs.python.org/3/library/functions.html#dir), I'm supposed to get a list of attributes. 
For example, If I'll run `dir(mne)` I will get: 

![image](https://user-images.githubusercontent.com/25877896/83053867-1c44e780-a05a-11ea-8a99-5af84f0c6ac0.png)

**Comment by deep-introspection** [comment]
@YannBeauxis Do you know how we can solve this?

**Comment by YannBeauxis** [comment]
Yes in the root `__init__.py` file, put some : 

```
from hypyp import viz, prep

__all__ = ["viz", "prep"]
```

I let you put what you want to get with dir(hypyp)

**Comment by deep-introspection** [comment]
Thanks @YannBeauxis! @AmirDJV does it work now with the new Github version?
