### ISSUE TITLE
Sampling frequency in compute_freq_bands function

### ISSUE THREAD

**Issue by deep-introspection** [GHFC/HyPyP#20]
Attention, in the compute_freq_bands function, the call to the mne.filter.filter_data should take the sampling frequency but [here](https://github.com/GHFC/HyPyP/blob/master/hypyp/analyses.py#L404) it is the number of samples which is given...

**Comment by phoebsc** [comment]
resolved by adding sampling frequency to compute_single_freq, compute_freq_bands and pair_connectivity
