### ISSUE TITLE
error in fit_params for ca_fit function 

### ISSUE THREAD

**Issue by ufangYang** [GHFC/HyPyP#25]
it seems there is a type error in ICA_fit() for the argument 'fit_params', even when I drop off the `extended=TRUE` or change to 'FALSE'

**Comment by ihgumilar** [comment]
There are two points here :
1. There is no explanation for `fit_params` when we press shift + tab
2. When I dropped the `fit_params` the ICA works. It seems that the argument of fit_params is not included in the function ?

![image](https://user-images.githubusercontent.com/49016400/84849280-0fd80b80-b0a9-11ea-8bf9-53bd51a4ade4.png)

**Comment by aayrolles** [comment]
I don't know why but you were true, the problem came from HyPyP version. We uninstall HyPyP and reinstall it with the `pip install HyPyP`. 
I think it could have been fix even without installing poetry.
