### ISSUE TITLE
error in plot_sensors_2d() 

### ISSUE THREAD

**Issue by YouyanLee** [GHFC/HyPyP#26]
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-55-8c8e90f19c99> in <module>()
     10 plt.gca().set_aspect('equal', 'box')
     11 plt.axis('off')
---> 12 viz.plot_sensors_2d(epo1, epo2,lab=True)  # bads are represented as squares
     13 # plotting links according to sign (red for positive values,
     14 # blue for negative) and value (line thickness increases

TypeError: plot_sensors_2d() got an unexpected keyword argument ['lab'`]

**Comment by deep-introspection** [comment]
@YouyanLee Did you try to reinstall the last version of HyPyP since we changed the parameters of the plot_sensors_2d function.
