### ISSUE TITLE
Fix mpl3d dependency

### ISSUE THREAD

**Issue by YannBeauxis** [GHFC/HyPyP#27]
`mpl3d` ( https://github.com/rougier/matplotlib-3d ) is required for `viz` module but is currently available only with git and does not exist in PyPi. This lib is quite eager and its maintainability need to be secure for a stable version of HyPyP.

- [ ] Check commitment and plans for the lib of the mpl3d developers

- [ ] deploy the mpl3d on PyPi

**Comment by aayrolles** [comment]
Hi, We have modified the visualization to no longer be dependent on mapl3d. For the moment in `master` the two possibilities of visualization still exist. And we can use either headmodel from mpl3D or the new and more simple topographic map. But we also can decide to delete completely mpl3D for futher version.

**Comment by deep-introspection** [comment]
@aayrolles Maybe the best would be to check with @Rougier what are his plans for the mpt3d library. If it's put on pypi, then we can keep it.

**Comment by rougier** [comment]
That's the mid-term plan but not before September I would say. In the meantime ang given the small size of mpl3d, you might consider to include the source in your package. Can you open an issue on mpl3D for requesting the PyPi (else I might forget)?
