### ISSUE TITLE
Check connectivity calculations

### ISSUE THREAD

**Issue by deep-introspection** [GHFC/HyPyP#7]
We need to understand from where do the differences in iCOH and PPC come from before merging the new calculation into _master_ branch.

Notebook in the _matrix_compute_ branch: [DEMO_compute_sync_test.ipynb](https://github.com/GHFC/HyPyP/blob/matrix_compute/hypyp/tests/DEMO_compute_sync_test.ipynb)

**Comment by phoebsc** [comment]
ICOH and COH are fixed, but PPC will be omitted for the alpha version.
